//
// Created by defacto on 2016.01.13..
//

#ifndef PWASTEROIDS_SUBMENU_H
#define PWASTEROIDS_SUBMENU_H

enum SUBMENU { SUBMENU_MAIN, SUBMENU_PLAY, SUBMENU_OPTIONS, SUBMENU_ABOUT, SUBMENU_GAME
};

#endif //PWASTEROIDS_SUBMENU_H
