//
// Created by defacto on 2016.01.13..
//

#ifndef PWASTEROIDS_OPTIONSMENUSCREENEVENTINTERPRETER_H
#define PWASTEROIDS_OPTIONSMENUSCREENEVENTINTERPRETER_H


class OptionsMenuScreenEventInterpreter {

};


#endif //PWASTEROIDS_OPTIONSMENUSCREENEVENTINTERPRETER_H
