//
// Created by root on 2016.01.20..
//

#ifndef PWASTEROIDS_ASTEROIDCOLLISIONENDTOENDTESTS_H
#define PWASTEROIDS_ASTEROIDCOLLISIONENDTOENDTESTS_H


class AsteroidCollisionEndToEndTests {

};


#endif //PWASTEROIDS_ASTEROIDCOLLISIONENDTOENDTESTS_H
